const TEST_ACTION = 'TEST_ACTION';
const TEST_ACTION_SUCCESS = 'TEST_ACTION_SUCCESS';
const TEST_ACTION_FAILED = 'TEST_ACTION_FAILED';

export { TEST_ACTION, TEST_ACTION_SUCCESS, TEST_ACTION_FAILED };
